### ISSUE TITLE
Plugin error with custom system commands

### ISSUE THREAD

**Issue by mcamou** [fabianonline/OctoPrint-Telegram#109]
I have a couple of custom system commands that work correctly on the web interface but not from the Telegram plugin:

```
system:
  actions:
  - action: printeron
    command: /home/pi/bin/printerOn
    confirm: false
    name: Printer on
  - action: printeroff
    command: /home/pi/bin/printerOff
    confirm: Are you sure you want to power off the printer?
    name: Printer off
```

This is the `printerOn` script (`printerOff` is similar):

```
#!/bin/sh
curl --header ''Content-Type: text/plain'' --data ON http://openhab.local:8080/rest/items/Magrathea_OnOff
sleep 10
$HOME/oprint/bin/octoprint client command api/connection connect
```

This is the error I get in `octoprint.log` with these commands (built-in commands like "Restart Octoprint" work fine):

```
2018-01-26 11:04:46,881 - octoprint.plugins.telegram.listener - INFO - Got a command: '/sys' with parameter: '9ed49207baf9d20a975a92c3f4b9005e' in chat 370432613
2018-01-26 11:04:47,208 - octoprint.plugins.telegram.listener - ERROR - Exception caught! coercing to Unicode: need string or buffer, bool found  
```
